# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - flaskappnew

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://flaskdockernew.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_a332996315be464688f4850e1bdaed92 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_6bea30952e5b4069a665a9be0a5a104a }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: flaskdockernew.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_a332996315be464688f4850e1bdaed92 }}/flaskpythondocker:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'flaskappnew'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_bc4340cc35a54e6bb611eb0187bde731 }}
        images: 'flaskdockernew.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_a332996315be464688f4850e1bdaed92 }}/flaskpythondocker:${{ github.sha }}'